use GedControlDataBase;

ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_IE_CASSADO DEFAULT (0) FOR CLI_IE_CASSADO
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_ATIVO_FISCAL DEFAULT (1) FOR CLI_ATIVO_FISCAL
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_ATIVO_CONTABIL DEFAULT (1) FOR CLI_ATIVO_CONTABIL
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_ATIVO_PESSOAL DEFAULT (1) FOR CLI_ATIVO_PESSOAL
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_DESLIGAMENTO_TIPO DEFAULT (0) FOR CLI_DESLIGAMENTO_TIPO
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_PERFIL_ATUAL_CLASSIFICACAO DEFAULT (0) FOR CLI_PERFIL_ATUAL_CLASSIFICACAO
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_PERFIL_ATUAL_COMERCIO DEFAULT (0) FOR CLI_PERFIL_ATUAL_COMERCIO
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_PERFIL_ATUAL_INDUSTRIA DEFAULT (0) FOR CLI_PERFIL_ATUAL_INDUSTRIA
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_PERFIL_ATUAL_SERVICO DEFAULT (0) FOR CLI_PERFIL_ATUAL_SERVICO
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_PERFIL_ATUAL_PROLABORE DEFAULT (0) FOR CLI_PERFIL_ATUAL_PROLABORE
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_PERFIL_ATUAL_FOLHA DEFAULT (0) FOR CLI_PERFIL_ATUAL_FOLHA
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_PERFIL_ATUAL_BALANCOS DEFAULT (0) FOR CLI_PERFIL_ATUAL_BALANCOS
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_PERFIL_ATUAL_BLOQUADO DEFAULT (0) FOR CLI_PERFIL_ATUAL_BLOQUEADO
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_PERFIL_ATUAL_SEMMOVIMENTO DEFAULT (0) FOR CLI_PERFIL_ATUAL_SEMMOVIMENTO
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_PERFIL_ATUAL_PORTE DEFAULT (0) FOR CLI_PERFIL_ATUAL_PORTE
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_PERFIL_ATUAL_TIPO DEFAULT (0) FOR CLI_PERFIL_ATUAL_TIPO
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_INATIVO DEFAULT (0) FOR CLI_INATIVO
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_DEPOSITO DEFAULT (0) FOR CLI_DEPOSITO
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_UNI_PROFISSIONAL DEFAULT (0) FOR CLI_UNI_PROFISSIONAL
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_FISCAL_CELULAR1_ACEITA_SMS DEFAULT (0) FOR CLI_FISCAL_CELULAR1_ACEITA_SMS
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_CONTABIL_CELULAR1_ACEITA_SMS DEFAULT (0) FOR CLI_CONTABIL_CELULAR1_ACEITA_SMS
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_PESSOAL_CELULAR1_ACEITA_SMS DEFAULT (0) FOR CLI_PESSOAL_CELULAR1_ACEITA_SMS
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_FINANCEIRO_CELULAR1_ACEITA_SMS DEFAULT (0) FOR CLI_FINANCEIRO_CELULAR1_ACEITA_SMS
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_IMPOSTO_RENDA_OPCAO DEFAULT (0) FOR CLI_IMPOSTO_RENDA_OPCAO
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_DECIMO_TERCEIRO_OPCAO DEFAULT (0) FOR CLI_DECIMO_TERCEIRO_OPCAO
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_PERFIL_ATUAL_IMUNE DEFAULT (0) FOR _CLI_PERFIL_ATUAL_IMUNE
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_PERFIL_ATUAL_INATIVA DEFAULT (0) FOR CLI_PERFIL_ATUAL_INATIVA
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_PERFIL_ATUAL_DESONERACAO_FOLHA DEFAULT (0) FOR CLI_PERFIL_ATUAL_DESONERACAO_FOLHA
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_PERFIL_ATUAL_FORMA_TRIBUTACAO_IRPJ DEFAULT (0) FOR CLI_PERFIL_ATUAL_FORMA_TRIBUTACAO_IRPJ
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_PERFIL_ATUAL_DECIMO_TERCEIRO DEFAULT (0) FOR CLI_PERFIL_ATUAL_DECIMO_TERCEIRO
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_TESTE DEFAULT (0) FOR CLI_TESTE
ALTER TABLE Clientes ADD CONSTRAINT DF__Clientes__CLI_LO__31CD3CEC DEFAULT (0) FOR CLI_LOCACAO
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_PERMITIR_UPLOAD_AVULSO DEFAULT (0) FOR CLI_PERMITIR_UPLOAD_AVULSO
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_UNIFICAR_RETENCOES DEFAULT (0) FOR CLI_UNIFICAR_RETENCOES
ALTER TABLE Clientes ADD CONSTRAINT DF_Clientes_CLI_UNIFICAR_RETENCOES_MATRIZ DEFAULT (0) FOR CLI_UNIFICAR_RETENCOES_MATRIZ
ALTER TABLE Clientes ADD CONSTRAINT CK_Clientes_CLI_PORTE CHECK (CLI_PORTE='G' OR CLI_PORTE='M' OR CLI_PORTE='P')
ALTER TABLE Clientes ADD CONSTRAINT CK_Clientes_CLI_TIPO CHECK (CLI_TIPO='C' OR CLI_TIPO='B' OR CLI_TIPO='A')


ALTER TABLE LoginsInternos ADD CONSTRAINT DF_LoginsInternos_LOGI_PWD DEFAULT ('1234') FOR LOGI_PWD
ALTER TABLE LoginsInternos ADD CONSTRAINT DF_LoginsInternos_LOGI_ATIVO DEFAULT (1) FOR LOGI_ATIVO
ALTER TABLE LoginsInternos ADD CONSTRAINT DF_LoginsInternos_LOGI_SUPERVISOR DEFAULT (0) FOR LOGI_SUPERVISOR
ALTER TABLE LoginsInternos ADD CONSTRAINT DF_LoginsInternos_LOGI_HOME_OFFICE DEFAULT (0) FOR LOGI_HOME_OFFICE
ALTER TABLE LoginsInternos ADD CONSTRAINT DF_LoginsInternos_LOGI_AUDITOR DEFAULT (0) FOR LOGI_AUDITOR
ALTER TABLE LoginsInternos ADD CONSTRAINT DF_LoginsInternos_LOGI_DIRETORIA DEFAULT (0) FOR LOGI_DIRETORIA
ALTER TABLE LoginsInternos ADD CONSTRAINT DF_LoginsInternos_LOGI_PROGRAMACAO DEFAULT (0) FOR LOGI_PROGRAMACAO
ALTER TABLE LoginsInternos ADD CONSTRAINT DF_LoginsInternos_LOGI_TESTE DEFAULT (0) FOR LOGI_TESTE
ALTER TABLE LoginsInternos ADD CONSTRAINT DF_LoginsInternos_LOGI_PRAZO_ACRESCENTAR DEFAULT (0) FOR LOGI_PRAZO_ACRESCENTAR
ALTER TABLE LoginsInternos ADD CONSTRAINT DF_LoginsInternos_LOGI_RECEBER_AVISO_ALTERACAO_PERFIL DEFAULT (1) FOR LOGI_RECEBER_AVISO_ALTERACAO_PERFIL


ALTER TABLE LoginsExternos ADD  CONSTRAINT DF_LoginsExternos_LOGE_FISCAL  DEFAULT ((1)) FOR LOGE_FISCAL
ALTER TABLE LoginsExternos ADD  CONSTRAINT DF_LoginsExternos_LOGE_CONTABIL  DEFAULT ((1)) FOR LOGE_CONTABIL
ALTER TABLE LoginsExternos ADD  CONSTRAINT DF_LoginsExternos_LOGE_PESSOAL  DEFAULT ((1)) FOR LOGE_PESSOAL
ALTER TABLE LoginsExternos ADD  CONSTRAINT DF_LoginsExternos_LOGE_LEGALIZACOES  DEFAULT ((1)) FOR LOGE_LEGALIZACOES
ALTER TABLE LoginsExternos ADD  CONSTRAINT DF_LoginsExternos_LOGE_GED  DEFAULT ((0)) FOR LOGE_GED
ALTER TABLE LoginsExternos ADD  CONSTRAINT DF_LoginsExternos_LOGE_DIRETORIO  DEFAULT ((0)) FOR LOGE_DIRETORIA
ALTER TABLE LoginsExternos ADD  CONSTRAINT DF_LoginsExternos_LOGE_PODE_ALTERAR_DADOS  DEFAULT ((0)) FOR LOGE_PODE_ALTERAR_DADOS
--ALTER TABLE LoginsExternos ADD  CONSTRAINT DF_LoginsExternos_LOGE_PWD  DEFAULT (fn_random_password()) FOR LOGE_PWD
ALTER TABLE LoginsExternos ADD  CONSTRAINT DF_LoginsExternos_LOGE_AGUARDANDO_CONFIRMACAO  DEFAULT ((0)) FOR LOGE_AGUARDANDO_CONFIRMACAO
ALTER TABLE LoginsExternos ADD  CONSTRAINT DF_LoginsExternos_LOGE_CELULAR_ACEITA_SMS  DEFAULT ((1)) FOR LOGE_CELULAR_ACEITA_SMS

ALTER TABLE LoginsExternosEmpresas ADD CONSTRAINT FK_LoginsExternosEmpresas_Clientes FOREIGN KEY (LOGEE_EMPRESA) REFERENCES Clientes (CLI_IND)
ALTER TABLE LoginsExternosEmpresas CHECK CONSTRAINT FK_LoginsExternosEmpresas_Clientes
ALTER TABLE LoginsExternosEmpresas ADD CONSTRAINT FK_LoginsExternosEmpresas_LoginsExternos FOREIGN KEY (LOGEE_LOGIN_EXTERNO) REFERENCES LoginsExternos (LOGE_IND)
ALTER TABLE LoginsExternosEmpresas CHECK CONSTRAINT FK_LoginsExternosEmpresas_LoginsExternos