--create database GedScannerTwain
use GedScannerTwain;

CREATE TABLE PlanoConta(
	PLAN_IND INT IDENTITY, 
	PLAN_DESCRICAO VARCHAR(100) NOT NULL, 
	PLAN_CODIGO VARCHAR(10) NOT NULL, 
	PLAN_FECHADO BIT NOT NULL, 
	PLAN_DT_INICIO DATETIME NOT NULL, 
	PLAN_LOGININSERT INT NOT NULL, 
	CONSTRAINT PK_PlanoConta PRIMARY KEY (PLAN_IND)
);

CREATE TABLE ContaTipo(
	CONTP_IND INT IDENTITY,
	CONTP_DESCRICAO VARCHAR(100) NOT NULL,
	CONTP_CLASSIFICADOR VARCHAR(15) NOT NULL, 
	CONTP_DT_INICIO DATETIME NOT NULL, 
	CONTP_LOGININSERT INT NOT NULL, 
	CONSTRAINT PK_ContaTipo PRIMARY KEY (CONTP_IND)
);

CREATE TABLE Conta(
	CONT_IND INT IDENTITY, 
	CONT_DESCRICAO VARCHAR(100) NOT NULL, 
	CONT_ACESSO VARCHAR(7) NOT NULL, 
	CONT_CONTATIPO INT NOT NULL, 
	CONT_DT_INICIO DATETIME NOT NULL, 
	CONT_LOGININSERT INT NOT NULL, 
	CONSTRAINT PK_Conta PRIMARY KEY (CONT_IND), 
	CONSTRAINT FK_Conta_ContaTipo FOREIGN KEY (CONT_CONTATIPO) REFERENCES ContaTipo (CONTP_IND)
);

CREATE TABLE PlanContConta(
	PCONT_IND INT IDENTITY, 
	PCONT_CONTA INT NOT NULL, 
	PCONT_PLANOCONTA INT NOT NULL, 
	PCONT_DT_INICIO DATETIME NOT NULL, 
	PCONT_LOGININSERT INT NOT NULL, 
	CONSTRAINT PK_PlanContConta PRIMARY KEY (PCONT_IND),
	CONSTRAINT FK_PlanContConta_Conta FOREIGN KEY (PCONT_CONTA) REFERENCES Conta (CONT_IND),
	CONSTRAINT FK_PlanContConta_PlanoConta FOREIGN KEY (PCONT_PLANOCONTA) REFERENCES PlanoConta (PLAN_IND)
);

CREATE TABLE GedArquivoTipo(
	GEDTIPO_IND INT IDENTITY,
	GEDTIPO_DESCRICAO VARCHAR(100) NOT NULL,
	GEDTIPO_EXPORTA BIT NOT NULL,
	GEDTIPO_DT_INICIO DATETIME NOT NULL, 
	GEDTIPO_LOGININSERT INT NOT NULL, 
	GEDTIPO_PAI INT NULL,
	CONSTRAINT PK_GedArquivoTipo PRIMARY KEY (GEDTIPO_IND), 
	CONSTRAINT FK_GedArquivoTipo_PAI FOREIGN KEY (GEDTIPO_PAI) REFERENCES GedArquivoTipo (GEDTIPO_IND)
);

CREATE TABLE GedCampoTipo(
	CAPTIP_IND INT IDENTITY,
	CAPTIP_DESCRICAO VARCHAR(100) NOT NULL,
	CONSTRAINT PK_GedCampoTipo PRIMARY KEY (CAPTIP_IND)
);

CREATE TABLE GedCampo(
	CAMP_IND INT IDENTITY,
	CAMP_DESCRICAO VARCHAR(100) NOT NULL,
	CAMP_ARQUIVOTIPO INT NOT NULL,
	CAMP_TIPO INT NOT NULL, 
	CAMP_DT_INICIO DATETIME NOT NULL, 
	CAMP_LOGININSERT INT NOT NULL, 
	CAMP_OBRIGATORIO BIT NOT NULL, 
	CONSTRAINT PK_GedCampo PRIMARY KEY (CAMP_IND),
	CONSTRAINT FK_GedCampo_GedArquivoTipo FOREIGN KEY (CAMP_ARQUIVOTIPO) REFERENCES GedArquivoTipo (GEDTIPO_IND),
	CONSTRAINT FK_GedCampo_GedCampoTipo FOREIGN KEY (CAMP_TIPO) REFERENCES GedCampoTipo (CAPTIP_IND)
);

CREATE TABLE ContArqTipo(
	CATIP_IND INT IDENTITY,
	CATIP_PLANCONTCONTA INT NOT NULL,
	CATIP_ARQUIVOTIPO INT NOT NULL,
	CATIP_DT_INICIO DATETIME NOT NULL, 
	CATIP_LOGININSERT INT NOT NULL, 
	CONSTRAINT PK_ContArqTipo PRIMARY KEY (CATIP_IND), 
	CONSTRAINT FK_ContArqTipo_PlanContConta FOREIGN KEY (CATIP_PLANCONTCONTA) REFERENCES PlanContConta (PCONT_IND),
	CONSTRAINT FK_ContArqTipo_GedArquivoTipo FOREIGN KEY (CATIP_ARQUIVOTIPO) REFERENCES GedArquivoTipo (GEDTIPO_IND)
);

CREATE TABLE GedCampoValor(
	CAPVAL_IND INT IDENTITY,
	CAPVAL_CAMPO INT NOT NULL,
	CAPVAL_CONTARQUIVOSTIPO INT NOT NULL,
	CAPVAL_VALOR VARCHAR(MAX) NOT NULL,
	CAPVAL_ATUAL BIT NOT NULL,
	CAPVAL_DATA DATETIME NOT NULL,
	CONSTRAINT PK_GedCampoValor PRIMARY KEY (CAPVAL_IND),
	CONSTRAINT FK_GedCampoValor_GedCampo FOREIGN KEY (CAPVAL_CAMPO) REFERENCES GedCampo (CAMP_IND),
	CONSTRAINT FK_GedCampoValor_ContArqTipo FOREIGN KEY (CAPVAL_CONTARQUIVOSTIPO) REFERENCES ContArqTipo (CATIP_IND)
);

CREATE TABLE GedLote(
	GLOTE_IND INT IDENTITY,
	GLOTE_DESCRICAO VARCHAR(100) NOT NULL, 
	GLOTE_DISPONIVELEM SMALLDATETIME NOT NULL, 
	GLOTE_DISPONIVELPOR INT NOT NULL,
	GLOTE_FECHADOEM SMALLDATETIME NULL, 
	GLOTE_FECHADOPOR INT NULL,
	GLOTE_ENVIADO BIT NOT NULL, 
	CONSTRAINT PK_GedLote PRIMARY KEY (GLOTE_IND)
);

CREATE TABLE GedDocumento(
	GEDDOC_IND int identity NOT NULL, 
	GEDDOC_DESCRICAO nvarchar(100) NOT NULL,
	GEDDOC_CONTARQUIVOTIPO int, 
	GEDDOC_LOTE int NOT NULL, 
	CONSTRAINT PK_GedDocumento PRIMARY KEY (GEDDOC_IND), 
	CONSTRAINT FK_GedDocumento_ContArqTipo FOREIGN KEY (GEDDOC_CONTARQUIVOTIPO) REFERENCES ContArqTipo (CATIP_IND)
);

CREATE TABLE GedArquivo(
	GEDARQ_IND int identity NOT NULL,
	GEDARQ_DISPONIVELEM smalldatetime NOT NULL,
	GEDARQ_DISPONIVELPOR int NOT NULL,
	GEDARQ_ARQUIVO image NOT NULL,
	GEDARQ_TAMANHO bigint NOT NULL,
	GEDARQ_EXTENSAO varchar(5) NOT NULL,
	GEDARQ_DESCRICAO nvarchar(100) NOT NULL,
	GEDARQ_ACESSOEM smalldatetime NULL,
	GEDARQ_ACESSOPOR int NULL,
	GEDARQ_DOCUMENTO INT NOT NULL,
	CONSTRAINT PK_GedArquivo PRIMARY KEY (GEDARQ_IND), 
	CONSTRAINT FK_GedArquivo_GedDocumento FOREIGN KEY (GEDARQ_DOCUMENTO) REFERENCES GedDocumento (GEDDOC_IND)
);



